language: python
python:
 - "2.7"
env:
 - DJANGO_VERSION=1.6.2
 - DJANGO_TEST_TEMP_DIR=slack/settings
install:
 - pip install -q -r requirements/test.txt
script:
 - python manage.py test --settings=slack.settings.test
