language: python
python:
 - "2.7"
env:
 global:
   - DJANGO_TEST_TEMP_DIR=`pwd`"/slack/settings"
 matrix:
   - DJANGO_VERSION=1.6.2
install:
 - pip install -q -r requirements/test.txt
script:
 - python manage.py test --settings=slack.settings.test
